CREATE TABLE books (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  year SMALLINT NOT NULL
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO books (title, year)
VALUES ('The Hobbit', 1937);

SELECT *
FROM books;
